# @package _global_

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: "val/acc_best"

hydra:
  mode: "MULTIRUN"

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1
    direction: maximize
    n_trials: 100

    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 10

    params:
      data.batch_size: choice(16, 32, 64, 128, 256)
      model.optimizer.lr: log(interval(1e-5, 1e-2))
      model.optimizer.weight_decay: log(interval(1e-6, 1e-2))
      model.scheduler.factor: interval(0.05, 0.5)
      model.scheduler.patience: int(interval(5, 20))
      model.net.pretrained: choice(True, False)
      model.net.freeze_layers: choice(True, False)
      model.net.dropout_value: interval(0.2, 0.7)
