_target_: src.models.lit_module.LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
  momentum: 0.9694882833050156

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.coatnet.CoaTNet
  num_classes: 196
  pretrained: true
  freeze_layers: true
  dropout_value: 0.5
